### ISSUE TITLE
Reducing memory footprint

### ISSUE THREAD

**Issue by carlryn** [oegedijk/explainerdashboard#68] opened 2021-01-12 18:24 UTC
Hej,

In our application, we approximately have 300k samples and many dimensions. Therefore, when running the dashboard RAM becomes a problem. After going through the source code I am considering a few ways to decrease the memory footprint.

1. After computing properties removing for example 90% of the data on an individual level for the non-aggregating properties(also X and Y). The effect would be to lose the possibility for an individual explanation on the removed samples. Also, performance metrics such as precision and recall would be impacted.
2. Similar to 1 but using a database as storage for properties on an individual level. The implication would be that some callbacks need to query a database for data.
3. Changing some of the datatypes. E.g int64 to int32. This should probably not be a part of the explainerdashboard package though.

I haven't implemented any of these alternatives yet. Do you have any opinions or other ideas on how to do this best? :)

**Comment by oegedijk** [comment] 2021-01-12 19:21
Yeah, good points, had just added this to TODO.md today :) 

I was mainly thinking in terms of point 3: can convert to float32, or maybe even float16, use the pd.category dtype for categorical features, int8 for classifier labels, etc. Also right now everything is duplicated for having either group cats or not (all the `_cats` properties in the source code), so could probably set a `cats_only` parameter to only keep the grouped cats version. And right now I also duplicate the non-categorical columns, which is probably not necessary.

Point 1) I'm not so sure about. Think you would lose a lot of functionality. Basically all you are left with is some static figures. A lot of the point of the dashboard is that it's interactive, for which you need to recalculate things and so need the individual data. But you also want the dashboard to be responsive so that's why you want to pre-calculate and store. 

Point 2) could be an option, but could be quite a lot of work. Could keep it simple with a SQLite database. Or use a redis db. Would still be in-memory, but could be shared across workers/nodes. Or maybe store tables to file and use https://github.com/vaexio/vaex?

**Comment by oegedijk** [comment] 2021-01-13 07:58
Was thinking that maybe a neat way around this is to use only a sample (10.000 rows should be enough) for the explainer in order to calcualte importances, performance, plot dependence graphs, etc, and then retrieve the individual data from somewhere else.

So could add two methods like this:

```python
def get_index_list(self):
  return self.idxs.tolist()

def get_X_row(self, index):
  return self.X.iloc[[index]]
```

And then the end user could simply monkey patch these with methods that access their favourite data storage solution, sqlite, redis, some NoSQL database, their corporate oracle database, whatever, and return a row. That way you could show individual predictions for millions of rows without having to store these into memory...

```python
def get_index_list(self):
  # connect to database
  # get list of indexes
  return index_list

def get_X_row(self, index):
  # connect to database
  # retrieve row
  return X_row

ClasssifierExplainer.get_index_list = get_index_list
ClassifierExplainer.get_X_row = get_X_row
```

**Comment by carlryn** [comment] 2021-01-13 15:01
It's a quick fix. Definitely think loading individual samples from a database would be the best approach since it works as data scales. 
Metrics such as precision and recall could also be computed by querying the database/storage used.

**Comment by carlryn** [comment] 2021-01-13 16:01
However, in our specific use-case I think running shap-values on all data, and then selecting 10k for visualization and interpretation makes the most sense. It could be that you get the same overall picture if you run with 10k and 300k though. Will have to do some experimentation on it.

**Comment by carlryn** [comment] 2021-01-13 17:17
Let me know if you want a pull request for my implementation.

**Comment by oegedijk** [comment] 2021-01-13 19:03
sure! submit if you have something workable! 

I think we can easily get a 50% reduction simply by being a bit smarter how data is stored inside the explainer. The next step is then finding a good interface with outside storage solutions.

**Comment by oegedijk** [comment] 2021-01-14 15:27
I've also started on it, and it involves quite an intensive rewrite of the basic building blocks of the library. So I suggest you hold off on the PR until I've done this rewrite :)

**Comment by yanhong-zhao-ef** [comment] 2021-01-18 15:14
Great to see this discussion - I am also using it with quite a large data file and being able to query from DB for specific examples will definitely reduce the need or else booting the dashboard will take ages to begin with

**Comment by oegedijk** [comment] 2021-01-18 21:18
Started working on it. You can find progress in the dev branch: https://github.com/oegedijk/explainerdashboard/tree/dev It's a major rewrite with lots of breaking changes on the innards (although high level API should mostly works as before), so this will be version 0.3. For now only reworked the RegressionExplainer.

Basically:
- removed the `cats` option from the dashboard: onehot columns will always be merged. This both reduces the complexity of the underlying code, and saves a lot on having to store everything twice, both merged and not merged.
- Added parameter `precision`. Defaults to `"float64"`, but setting it to `'float32'` should save you half the memory footprint.
- Onehot columns now get stored as `np.int8` (since they are only `0` or `1` anyway)
- categorical columns are stored as pd.categorical (similar to R factors)
- Only storing string index in `self.idxs`, all other dataframes and series have a simple `RangeIndex` to save space.

Added method `get_index_list()`, `get_X_row(index)` and `get_y(index)`. Normally these simply return the relevant data from `self.idxs`, `self.X` or `self.y`.

But you can set them with set functions. As a silly example here I store the test set to csv with `PassengerClass` set to 1 for all samples, and then write the getter function loading this csv:

```python
X_store = X_test.copy()
X_store.loc[:, "PassengerClass"] = 1
X_store['Fare'] = y_test
X_store['Index'] = test_names
X_store.to_csv("store_test.csv", index=False)

def index_list_func():
    return pd.read_csv("store_test.csv")['Index'].tolist()

def X_row_func(index):
    df = pd.read_csv("store_test.csv")
    return df[df.Index == index].drop(["Index", "Fare"], axis=1)

def y_func(index):
    df = pd.read_csv("store_test.csv")
    return df[df.Index == index]["Fare"].item()

explainer.set_index_list_func(index_list_func)
explainer.set_X_row_func(X_row_func)
explainer.set_y_func(y_func)
```

You would probably want to combine this with some kind of caching functionality, either with a redis memoize function, or just writing it to a dataframe inside the explainer, so that you don't have to make the I/O expensive calls to the disk/database too often. 

I also added a `memory_usage()` method. So that you can see which attributes are using the most memory:

![image](https://user-images.githubusercontent.com/27999937/104963102-15e4f080-59da-11eb-8f98-e377193d8e92.png)

You could use this method on explainers with the current version of the library as well:

```python
def memory_usage(self, cutoff=0):
        """returns a pd.DataFrame with the memory usage of each attribute of
        this explainer object"""
        def get_size(obj):
            def get_inner_size(obj):
                if isinstance(obj, pd.DataFrame):
                    return obj.memory_usage().sum()
                elif isinstance(obj, pd.Series):
                    return obj.memory_usage()
                elif isinstance(obj, pd.Index):
                    return obj.memory_usage()
                elif isinstance(obj, np.ndarray):
                    return obj.nbytes
                else:
                    return sys.getsizeof(obj)

            if isinstance(obj, list):
                return sum([get_inner_size(o) for o in obj])
            elif isinstance(obj, dict):
                return sum([get_inner_size(o) for o in obj.values()])
            else:
                return get_inner_size(obj)

        def size_to_string(num, suffix='B'):
            for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
                if np.abs(num) < 1024.0:
                    return "%3.1f%s%s" % (num, unit, suffix)
                num /= 1024.0
            return "%.1f%s%s" % (num, 'Yi', suffix)

        memory_df = pd.DataFrame(columns=['property', 'type', 'bytes', 'size'])
        for k, v in self.__dict__.items():
            memory_df = memory_df.append(dict(
                property=f"self.{k}", type=v.__class__.__name__, 
                bytes=get_size(v), size=size_to_string(get_size(v))), 
                ignore_index=True)
        
        print("Explainer total memory usage (approximate): ", 
                    size_to_string(memory_df.bytes.sum()), flush=True)
        return (memory_df[memory_df.bytes>cutoff]
                    .sort_values("bytes", ascending=False)
                    .reset_index(drop=True))
```

Will have to re-write the ClassifierExplainer as well, which is going to be more complicated due to having to keep track of multiple `pos_label` options. Think I will also add an option to drop all labels except one. 

If you have time and your models are regression models, could you see how much this reduces your memory footprints? Thoughts on the API to access external data sources?

**Comment by oegedijk** [comment] 2021-01-20 10:24
So `ClassifierExplainer` should now also work again in the `dev` branch! 

And added a new `keep_shap_pos_label_only(pos_label)` method that drops shap values and shap interactions for all labels except `pos_label`. This should significantly reduce memory usage, at the cost of shap dependence and shap interaction graphs only working for a single pos label.

Still have to rewrite all the tests though to deal with the thousand breaking changes I made for this release :)

**Comment by yanhong-zhao-ef** [comment] 2021-01-20 10:57
Thanks @oegedijk  will check it out later! but yeah can see why that gives so much breaking changes but really like that memory using function!

**Comment by oegedijk** [comment] 2021-01-20 11:10
Also used the fact that if I'm going to make one breaking change, then I might as well do **all** the breaking changes :) 

Mostly at the `Explainer` level though, the higher level Dashboard API should work as before.

**Comment by oegedijk** [comment] 2021-01-24 14:42
Hi all,

I  just released a release candidate for version `0.3`, you can install it with `pip install explainerdashboard==0.3.0rc1`. @carlryn @yanhong-zhao-ef if you have time could you maybe try it out and let me know if anything has broken? (all tests are passing, but with so many breaking changes, I could easily miss something). You'll have to rebuild all the explainers you stored to file as there are a ton of breaking changes. (should give you a warning when you try to use an old one though)

@raybellwaves I'm not sure how to do a release candidate on conda, but maybe you also have time to kick the tires of the pip version... And congrats on the new job! :)

# release notes:

## 0.3.0:
This is a major release and comes with lots of breaking changes to the lower level 
explainer API. The higherlevel `ExplainerComponent` and `ExplainerDashboard` API has not been
changed however, except for the deprecation of the `cats` and `hide_cats` parameters.

Explainers generated with version `explainerdashboard <= 0.2.20.1` will not work 
with this version, so if you have stored explainers to disk you either have to 
rebuild them, or downgrade back to `explainerdashboard==0.2.20.1`! (hope you 
pinned your dependencies in production!)

Main motivation for these breaking changes was to improve memory usage of the
dashboards, especially in production. This lead to the deprecation of the
dual cats grouped/not grouped functionality of the dashboard. Once I had committed
to that breaking change, I decided to clean up the entire API and do all the 
needed breaking changes at once. 


### Breaking Changes
- onehot encoded features are now merged by default. This means that the `cats=True`
    parameter has been removed from all explainer methods, and the `group cats` 
    toggle has been removed from all `ExplainerComponents`. This saves both
    on code complexity and memory usage. If you wish to see the see the individual
    contributions of onehot encoded columns, simply don't pass them to the 
    `cats` parameter upon construction.
- Deprecated explainer attributes:
    - `BaseExplainer`:
        - `self.shap_values_cats`
        - `self.shap_interaction_values_cats`
        - `permutation_importances_cats`
        - `self.get_dfs()`
        - `formatted_contrib_df()`
        - `self.to_sql()`
        - `self.check_cats()` 
        - `equivalent_col`
    - `ClassifierExplainer`:
        - `get_prop_for_label`

- Naming changes to attributes:
    - `BaseExplainer`:
        - `importances_df()` -> `get_importances_df()`
        - `feature_permutations_df()` -> `get_feature_permutations_df()`
        - `self.get_int_idx(index)` -> `self.get_idx(index)`
        - `self.importances_df()` -> `self.get_importances_df()`
        - `self.contrib_df()` -> `self.get_contrib_df()` *
        - `self.contrib_summary_df()` -> `self.get_summary_contrib_df()` *
        - `self.interaction_df()` -> `get_interactions_df()` *
        - `self.shap_values` -> `self.get_shap_values_df`
        - `plot_shap_contributions()` -> `plot_contributions()`
        - `plot_shap_summary()` -> `plot_importances_detailed()`
        - `plot_shap_dependence()` -> `plot_dependence()`
        - `plot_shap_interaction()` -> `plot_interaction()`
        - `plot_shap_interaction_summary()` -> `plot_interactions_detailed()`
        - `plot_interactions()` -> `plot_interactions_importance()`
        - `n_features()` -> `n_features`
        - `shap_top_interaction()` -> `top_shap_interactions` 
        - `shap_interaction_values_by_col()` -> `shap_interactions_values_for_col()`
    - `ClassifierExplainer`:
        - `self.pred_probas` -> `self.pred_probas()`
        - `precision_df()` -> `get_precision_df()` *
        - `lift_curve_df()` -> `get_liftcurve_df()` *
   -`RandomForestExplainer`/`XGBExplainer`:
        - `self.decision_trees` -> `self.shadow_trees`
        - `self.decisiontree_df()` -> `self.decisionpath_df()`
        - `self.decisiontree_summary_df()` -> `self.decisionpath_summary_df()`
        - `self.decision_path_file()` -> `self.decisiontree_file()`
        - `self.decision_path()` -> `self.decisiontree()`
        - `self.decision_path_encoded()` -> `self.decisiontree_encoded()`

### New Features
- new `Explainer` parameter `precision`: defaults to `'float64'`. Can be set to
    `'float32'` to save on memory usage.
- new `memory_usage()` method to show which internal attributes take the most memory.
- net `keep_shap_pos_label_only(pos_label)` method:
    - drops shap values and shap interactions for all labels except `pos_label`
    - this should significantly reduce memory usage.
- added `get_index_list()`, `get_X_row(index)`, and `get_y(index)` methods.
    - these can be overridden with `.set_index_list_func()`, `.set_X_row_func()`
        and `.set_y_func()`.
    - by overriding these functions you can for example sample observations 
        from a database or other storage instead of from `X_test`, `y_test`.
- added `max_cat_colors` parameters to `plot_shap_summary` and `plot_shap_dependence` and `plot_shap_interaction`
    - prevents plotting getting slow with categorical features with many categories.
    - defaults to 5
    - can be set as `**kwarg` to `ExplainerDashboard`
- adds category limits and sorting to `RegressionVsCol` component
- adds property `X_merged` that gives a dataframe with onehot columns merged.

### Bug Fixes
- shap dependence: when no point cloud, do not highlight!
- Fixed bug with calculating contributions plot/table for whatif component,
    when InputFeatures had not fully loaded, resulting in shap error.

### Improvements
- saving `X.copy()`, instead of using a reference to `X`
    - this would result in more memory usage in development
        though, so you can `del X_test` to save memory.
- encoding onehot columns as `np.int8` saving memory usage
- encoding categorical features as `pd.category` saving memory usage
- added base `TreeExplainer` class that `RandomForestExplainer` and `XGBExplainer` both derive from
    - will make it easier to extend tree explainers to other models in the future
        - e.g. catboost and lightgbm

**Comment by oegedijk** [comment] 2021-01-27 11:27
Just released another release candidate (`rc2`), that can be installed with

```pip install explainerdashboard==0.3.0rc2```

does some more memory savings especially for binary classifiers. (plus cool new graph popout buttons!)

If I don't hear about it breaking anything important, I'll just go ahead and release it :)

**Comment by oegedijk** [comment] 2021-01-27 15:04
Released the new version! (and already did a bug fix release as it turns out that some new features only work with pandas 1.2).

@carlryn I hope this will lower your memory requirements! 

Added some instructions to the readme:

https://github.com/oegedijk/explainerdashboard#minimizing-memory-usage

**Closed** 2021-02-03 12:50 UTC
