### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'columns'

### ISSUE THREAD

**Issue by apavlo89** [oegedijk/explainerdashboard#95] opened 2021-03-03 20:00 UTC
This looks amazing but I can't run it on my dataset. I get the following error:

```
runfile('E:/Machine Learning Projects/ML UFC/genetic_algorithm_cluster_UFC_database_TPOT.py', wdir='E:/Machine Learning Projects/ML UFC')
Traceback (most recent call last):

  File "E:\Machine Learning Projects\ML UFC\genetic_algorithm_cluster_UFC_database_TPOT.py", line 533, in <module>
    ExplainerDashboard(ClassifierExplainer(RandomForestClassifier().fit(X_train, y_train), X_test, y_test)).run()

  File "C:\Users\apavl\anaconda3\envs\neuro\lib\site-packages\explainerdashboard\explainers.py", line 1774, in __init__
    super().__init__(model, X, y, permutation_metric,

  File "C:\Users\apavl\anaconda3\envs\neuro\lib\site-packages\explainerdashboard\explainers.py", line 149, in __init__
    self.onehot_cols, self.onehot_dict = parse_cats(self.X, cats)

  File "C:\Users\apavl\anaconda3\envs\neuro\lib\site-packages\explainerdashboard\explainer_methods.py", line 103, in parse_cats
    all_cols = X.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'
```

Any idea why that is?

**Comment by oegedijk** [comment] 2021-03-03 20:02
From the looks of it you are passing a numpy array instead of a pandas dataframe as `X`. (need a dataframe in order to assign shap values to each feature, for which we need a column name)

**Comment by apavlo89** [comment] 2021-03-03 20:23
But I am loading a pandas dataframe :/ This is the code:

```
ufc_master_ds = pd.read_csv("E:/Machine Learning Projects/ML UFC/ufc-master.csv")
y = ufc_master_ds.Winner
ufc_master_ds.drop(['Winner'], axis=1, inplace = True)
X = ufc_master_ds
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state=2, shuffle = True, stratify=y)

model = ExtraTreesClassifier(bootstrap=True, criterion="entropy", max_features=0.1, min_samples_leaf=12, min_samples_split=12, n_estimators=100,random_state=2)
model.fit(X_train, y_train)
from explainerdashboard import ClassifierExplainer, ExplainerDashboard

ExplainerDashboard(ClassifierExplainer(model.fit(X_train, y_train), X_test, y_test)).run()
```

**Comment by apavlo89** [comment] 2021-03-03 21:49
Its something weird with my database as other databases I've loaded work fine. Any ideas as to why would be greatly appreciated!

**Comment by oegedijk** [comment] 2021-03-04 08:20
Hmm, that's weird. Normally `train_test_split` should return what you put in (so if input is dataframe, should output dataframes, if input is numpy array, should output numpy arrays).

But probably add a check

```
assert isinstance(X_train, pd.DataFrame)
```
And otherwise explicitly wrap them in dataframes:

```
X_train = pd.DataFrame(X_train, columns = X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)
```
Or do you have a really old version of sklearn that still only outputs numpy arrays?

**Comment by apavlo89** [comment] 2021-03-04 16:50
```
X_train = pd.DataFrame(X_train, columns = X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)
```

This fixed it! Now I have another issue I was hoping you could help. I want to run:

```
exported_pipeline = make_pipeline(
    SelectPercentile(score_func=f_classif, percentile=16),
    ExtraTreesClassifier(bootstrap=True, criterion="entropy", max_features=0.1, min_samples_leaf=12, min_samples_split=12, n_estimators=100)
)
```

I get the following error:

`ValueError: Pipeline does not return same number of columns as input, nor does it have a proper .get_feature_names() method! Try passing the final estimator in the pipeline seperately together with an already transformed dataframe.`

Would you happen to know how to run SelectPercentile(score_func=f_classif, percentile=16) separately? I keep trying different things but get errors... I've always done it in make_pipeline...

**Comment by apavlo89** [comment] 2021-03-04 17:30
Would also be great if make_pipeline was supported as its a bit of a pain to do things separately

**Comment by oegedijk** [comment] 2021-03-04 18:52
Hi @apavlo89, I agree that it would be cool to support sklearn pipelines and I've tried to get them to work, but the problem is with how they are internally structured: the stages of the pipeline forward numpy arrays instead of dataframes, and it doesn't track what the newly generated features should be called. 

There is a proposed fix for this with here: https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep007/proposal.html

Given that the dashboard needs to know the names of the features in order to give meaningful importance and dependence plots, that means that until that proposal is implemented it will only accept pipelines that do not add or remove any columns.

**Closed** 2021-03-04 18:52 UTC
